version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - jcblw
  ignore:
  - dependency-name: framer-motion
    versions:
    - 4.1.2
    - 4.1.3
  - dependency-name: "@chakra-ui/react"
    versions:
    - 1.5.0
  - dependency-name: "@docusaurus/preset-classic"
    versions:
    - 2.0.0-alpha.72
  - dependency-name: "@docusaurus/core"
    versions:
    - 2.0.0-alpha.72
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.134
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: graphql-middleware
    versions:
    - 6.0.5
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: kcd-scripts
    versions:
    - 8.1.0
    - 8.1.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
  registries:
  - npm-registry-npm-pkg-github-com
